# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ec2a3a4881e3ed600521527b11489aa106713555c77142c978ac0cd8cc608c10ed7b7907e7bc60a646ec63ebaa56cd5be98694dfee438218ed06abe81300a62

test:
  secret_key_base: b24a8a27888f4cf229535ffd51cd34022f517a5412e8e393b7f2ad84ccce9bdd68c74a19d60c8eeafded47619a20ffb0e77233c6a7d877e5f2068bffa93001ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
